name: Production Deployment to Azure VM

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        shell: bash
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          echo "Building and pushing Docker images with tag: $COMMIT_SHA"
          docker compose build --build-arg IMAGE_TAG=$COMMIT_SHA
          docker compose push

      - name: Add SSH host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Azure VM
        shell: bash
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          DEPLOY_DIR="/home/${{ secrets.SSH_USER }}/my-simple-app"

          echo "Deploying to ${{ secrets.SSH_HOST }} ..."

          # Sync files (rsync supports exclude)
          rsync -avz --exclude '.env' . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${DEPLOY_DIR}

          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<EOF
          cd ${DEPLOY_DIR} || exit 1

          cat <<ENV > .env
          MONGO_ADMIN_USER=${{ secrets.MONGO_ADMIN_USER }}
          MONGO_ADMIN_PASS=${{ secrets.MONGO_ADMIN_PASS }}
          IMAGE_TAG=${COMMIT_SHA}
          ENV

          docker system prune -af
          docker compose down --remove-orphans || true
          docker compose pull
          docker compose up -d

          echo "Deployment successful!"
          docker ps
          EOF