name: Production Deployment to Azure VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        shell: bash
        run: |
          echo "Building and pushing images..."
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker compose build --build-arg IMAGE_TAG=$COMMIT_SHA
          docker compose push

      - name: Add SSH host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Azure VM
        run: |
          echo "Connecting to Azure VM: ${{ secrets.SSH_HOST }}"
          
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          DEPLOY_DIR="/home/${{ secrets.SSH_USER }}/my-simple-app"
          
          # Create directory if it doesn't exist
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p ${DEPLOY_DIR}"
          
          # Use scp to copy the entire codebase to the remote VM
          # Exclude the local .env file
          scp -r --exclude=".env" . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${DEPLOY_DIR}

          ssh -i $SSH_AUTH_SOCK -l ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST }} << 'EOF'
            echo "Successfully connected to the Azure VM."
            
            cd "${DEPLOY_DIR}" || exit 1 # Fails if cd fails
            
            # Create or update .env file on VM
            echo "MONGO_ADMIN_USER=${{ secrets.MONGO_ADMIN_USER }}" > .env
            echo "MONGO_ADMIN_PASS=${{ secrets.MONGO_ADMIN_PASS }}" >> .env
            echo "IMAGE_TAG=${COMMIT_SHA}" >> .env

            docker system prune -af
            docker compose down --remove-orphans || true
            docker compose pull
            docker compose up -d
            
            echo "Deployment completed successfully!"
            docker ps || exit 1 # Fail if docker ps fails
            exit 0
          EOF

      - name: Cleanup SSH agent
        if: always()
        run: |
          ssh-agent -k