name: Production Deployment to Azure VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker images
        shell: bash
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker compose build --build-arg IMAGE_TAG=$COMMIT_SHA
      
      - name: Push images to Docker Hub
        run: docker compose push
      
      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Azure VM
        run: |
          echo "Connecting to Azure VM: ${{ secrets.SSH_HOST }}"
          
          # Use a variable for the commit SHA
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)

          # Copy .env and docker-compose.yml to the VM
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            mkdir -p ~/my-simple-app
            exit
          EOF
          scp .env ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/my-simple-app/.env
          scp docker-compose.yaml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/my-simple-app/docker-compose.yaml

          # Run deployment commands on the VM
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/my-simple-app
            echo "Deploying latest stack..."

            # Create or update .env file on VM
            echo "MONGO_ADMIN_USER=${{ secrets.MONGO_ADMIN_USER }}" > .env
            echo "MONGO_ADMIN_PASS=${{ secrets.MONGO_ADMIN_PASS }}" >> .env
            echo "IMAGE_TAG=${COMMIT_SHA}" >> .env

            docker system prune -af
            docker compose down
            docker compose pull
            docker compose up -d
            echo "Deployment completed successfully!"
            docker ps
          EOF

      - name: Cleanup SSH agent
        if: always()
        run: |
          ssh-agent -k