
name: CI/CD for Docker Compose App

on:
  push:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Compose file
        run: docker compose config

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build services
        
        run: |
          docker-compose build
          docker-compose down
          docker-compose up -d
          docker ps
          docker-compose logs          

  deploy:
    runs-on: self-hosted
    needs: build-test-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Deploy locally
        env:
          MONGO_ADMIN_USER: ${{ secrets.MONGO_ADMIN_USER }}
          MONGO_ADMIN_PASS: ${{ secrets.MONGO_ADMIN_PASS }}
        shell: bash
        run: |
          echo "Deploying latest stack..."
          docker system prune -af
          docker-compose --env-file .env down
          docker-compose --env-file .env up -d --build
          docker ps


  cleanup:
    runs-on: self-hosted
    needs: deploy
    if: always()
    steps:
      - name: Cleanup workspace
        run: |
          echo "Cleaning up runner workspace..."
          cd ~/actions-runner/_work
          rm -rf *