name: CI/CD for Docker Compose App

on:
  push:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build services
        run: docker-compose build

      - name: Run tests
        run: |
          docker-compose up -d
          sleep 10
          docker ps
          docker-compose logs
          # You can add curl or npm test commands here if app exposes APIs
          docker-compose down

  deploy:
    runs-on: self-hosted
    needs: build-test-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy locally
        shell: bash
        run: |
          echo "Deploying latest stack..."
          docker-compose down
          docker-compose up -d --build
          docker ps


  cleanup:
    runs-on: self-hosted
    needs: deploy
    if: always()
    steps:
      - name: Cleanup workspace
        run: |
          echo "Cleaning up runner workspace..."
          cd ~/actions-runner/_work
          rm -rf *