
name: CI/CD for Docker Compose App

on:
  push:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Compose file
        run: docker compose config


      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build services
        
        run: |
          docker compose build
          docker compose down
          docker compose up -d
          docker ps
          docker compose logs

  deploy:
    runs-on: self-hosted
    needs: build-test-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file for production
        run: |
          echo "MONGO_ADMIN_USER=${{ secrets.MONGO_ADMIN_USER }}" > .env
          echo "MONGO_ADMIN_PASS=${{ secrets.MONGO_ADMIN_PASS }}" >> .env
 
        # env:
        #   MONGO_ADMIN_USER: ${{ secrets.MONGO_ADMIN_USER }}
        #   MONGO_ADMIN_PASS: ${{ secrets.MONGO_ADMIN_PASS }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy locally
        shell: bash
        run: |
          echo "Deploying latest stack..."
          docker system prune -af
          docker compose push
          docker compose down
          docker compose pull
          docker compose up -d
          docker ps

  cleanup:
    runs-on: self-hosted
    needs: deploy
    if: always()
    steps:
      - name: Cleanup workspace
        run: |
          echo "Cleaning up runner workspace..."
          cd ~/actions-runner/_work
          rm -rf *

  